language: python

sudo: false

cache: pip

python:
  - '2.7'
  - 'pypy'
  - '3.5'

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install pycrypto; fi;
  - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then pip install -e .; fi;

before_script:
  - pip install coverage
  - pip install codecov
  - mysql -e 'create database pydal;'
  - psql -c 'create database pydal;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d pydal;
  - psql -c 'SHOW SERVER_VERSION' -U postgres


script: export COVERAGE_PROCESS_START=gluon/tests/coverage.ini; ./web2py.py --run_system_tests --with_coverage

after_success:
  - coverage combine;
  - codecov

notifications:
  email: true

addons:
  postgresql: "9.4"
